// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4zZBel2WmOSacKWWBcTQ2-SX6dVCkzjg',
    appId: '1:743227419762:web:ef2c7e3db4f24f099f26eb',
    messagingSenderId: '743227419762',
    projectId: 'pemmob-48aed',
    authDomain: 'pemmob-48aed.firebaseapp.com',
    databaseURL: 'https://pemmob-48aed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemmob-48aed.appspot.com',
    measurementId: 'G-918E2HWT85',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvEjLQpJMPgy5zSxiNO3w0-g3TILX4JI',
    appId: '1:743227419762:android:cb83e30658cbb64b9f26eb',
    messagingSenderId: '743227419762',
    projectId: 'pemmob-48aed',
    databaseURL: 'https://pemmob-48aed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemmob-48aed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk2bcjnsy_AbhdvQ1itrW14lG9pAjU3GQ',
    appId: '1:743227419762:ios:f0ca705bf1b4c7409f26eb',
    messagingSenderId: '743227419762',
    projectId: 'pemmob-48aed',
    databaseURL: 'https://pemmob-48aed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemmob-48aed.appspot.com',
    iosBundleId: 'com.example.rezzyPemob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk2bcjnsy_AbhdvQ1itrW14lG9pAjU3GQ',
    appId: '1:743227419762:ios:f0ca705bf1b4c7409f26eb',
    messagingSenderId: '743227419762',
    projectId: 'pemmob-48aed',
    databaseURL: 'https://pemmob-48aed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemmob-48aed.appspot.com',
    iosBundleId: 'com.example.rezzyPemob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4zZBel2WmOSacKWWBcTQ2-SX6dVCkzjg',
    appId: '1:743227419762:web:7ff0a47663c39faf9f26eb',
    messagingSenderId: '743227419762',
    projectId: 'pemmob-48aed',
    authDomain: 'pemmob-48aed.firebaseapp.com',
    databaseURL: 'https://pemmob-48aed-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemmob-48aed.appspot.com',
    measurementId: 'G-QBT2PSJMFD',
  );
}
